### ISSUE TITLE
스팟찍기 레이어

### ISSUE THREAD

**Issue by devjaewon** [Nexters/DaeDongYeoMap-Frontend#2]
## TODO

- [x] (지도) 마커 클릭시, 레이어 열림
- [x] (레이어 p1) 이모지 선택가능
- [x] (레이어 p1) 다음버튼 클릭시, p2 열림
- [x] (레이어 p2) 완료하기 클릭시, 스팟 생성
